### ISSUE TITLE
Errors when running online_prediction.py

### ISSUE THREAD

**Issue by qifanyyy** [tkdsheep/Intention-Mining-TSE#1]
hi.
 I try to run the script online_prediction.py with python2 and TensorFlow but I got "KeyError: "The name 'conv-maxpool-3' refers to an Operation not in the graph." I'm curious if I need to download extra tool to run this code. Any suggestion will be helpful. 
```
Traceback (most recent call last):
  File "/Users/yuqifan/Downloads/Intention-Mining-TSE-master/online_prediction.py", line 60, in <module>
    conv = graph.get_operation_by_name("conv-maxpool-3").outputs
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2446, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2318, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2378, in _as_graph_element_locked
    "graph." % repr(name))
```
Thanks!

**Comment by yebityon** [comment]
Hi.
I got the same error.
I commented out line 60 of online_prediction.py and it worked.
unfortunately, I am not familiar with TensorFlow, so I don't know this is good solution :( 
(but it seems like working...)
